// Module registry. Add a module here and it appears in the sidebar and router.
// `collection` ties a module to a data collection; `grad` picks its gradient from tokens in app.css.
export const MODULES = [
  { id: 'dashboard', label: 'Dashboard', grad: 'dashboard', phase: 3 },
  { id: 'profile', label: 'Profile', grad: 'dashboard', collection: 'student', phase: 2 },
  { id: 'achievements', label: 'Achievements', grad: 'achievements', collection: 'achievements', phase: 2,
    subs: [['all', 'All Achievements'], ['add', 'Add Achievement']] },
  { id: 'projects', label: 'Projects', grad: 'projects', collection: 'projects', phase: 2,
    subs: [['all', 'All Projects'], ['add', 'Add Project']] },
  { id: 'robotics', filterNav: { log: 'log', competitions: 'competitions', challenges: 'challenges' }, label: 'Robotics & Engineering', grad: 'robotics', collection: 'robotics', phase: 2,
    subs: [['log', 'Robotics Log'], ['competitions', 'Competitions'], ['challenges', 'Engineering Challenges']] },
  { id: 'coding', label: 'Coding / Python', grad: 'coding', collection: 'coding', phase: 2,
    subs: [['journal', 'Coding Journal'], ['add', 'Add Entry']] },
  { id: 'science', label: 'Science Investigations', grad: 'science', collection: 'science', phase: 2,
    subs: [['all', 'All Investigations'], ['add', 'Add Investigation']] },
  { id: 'maths', label: 'Mathematics & Problem Solving', grad: 'projects', collection: 'mathematics', phase: 2,
    subs: [['all', 'All Problems'], ['add', 'Add Problem']] },
  { id: 'spatial', label: 'Visual / Spatial Reasoning', grad: 'coding', collection: 'visualReasoning', phase: 2,
    subs: [['all', 'All Entries'], ['add', 'Add Entry']] },
  { id: 'challenges', label: 'STEM Challenges', grad: 'robotics', collection: 'stemChallenges', phase: 2,
    subs: [['all', 'All Challenges'], ['add', 'Add Challenge']] },
  { id: 'goals', label: 'Goals & Roadmap', grad: 'goals', collection: 'goals', phase: 2,
    subs: [['short', 'Short term (1–3 months)'], ['medium', 'Medium term (3–12 months)'], ['long', 'Long term (1–3 years)'], ['add', 'Add Goal']] },
  { id: 'reflections', label: 'Reflection Journal', grad: 'reflection', collection: 'reflections', phase: 2,
    subs: [['all', 'All Reflections'], ['add', 'Add Reflection']] },
  { id: 'skills', label: 'Skills Development', grad: 'goals', collection: 'skills', phase: 3 },
  { id: 'evidence', label: 'Evidence Library', grad: 'achievements', collection: 'evidence', phase: 2,
    subs: [['all', 'All Evidence'], ['add', 'Add Evidence']] },
  { id: 'sst', label: 'SST / DSA Preparation', grad: 'goals', collection: 'sstPrep', phase: 3 },
  { id: 'interviews', label: 'Interview Practice', grad: 'reflection', collection: 'interviews', phase: 2,
    subs: [['questions', 'Practice Questions'], ['add', 'Add Answer']] },
  { id: 'timeline', label: 'Development Timeline', grad: 'dashboard', phase: 3 },
  { id: 'reports', label: 'Reports', grad: 'science', phase: 4,
    subs: [['story', 'Cyllee Story'], ['gaps', 'What to develop next'], ['monthly', 'Monthly Review'], ['print', 'Printable Reports']] },
  { id: 'settings', label: 'Settings', grad: 'dashboard', phase: 1,
    subs: [['profile', 'Profile Settings'], ['appearance', 'Appearance'], ['backup', 'Backup & Restore'],
      ['pwa', 'Install App'], ['data', 'Data Management'], ['about', 'About']] },
].map(m => ({ ...m, subs: m.subs && m.subs.map(([id, label]) => ({ id, label })) }));
